version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.5
      - image: cimg/postgres:14.4-postgis
        environment:
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      -  run:
           name: Install required deps
           command: |
             sudo apt-get update -y
             sudo apt-get install build-essential binutils -y
             sudo apt-get install libgdal-dev libproj-dev gdal-bin python3-gdal cron \
             postgresql-client gettext postgresql postgresql-contrib postgis -y
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: python manage.py test
      - run:
          name: Build docker image
          command: |
            docker-compose build
            docker images
            docker container run --name shopwithcircleci shopwithcircleci -e DATABASE_URL=hello python manage.py test

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint