version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.5
      - image: cimg/postgres:14.4-postgis
        environment:
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      -  run:
           name: Install Host Machine Dependencies (ie packages)
           command: |
             sudo apt-get update -y
             sudo apt-get install python3-dev build-essential binutils -y
             sudo apt-get upgrade -y
             sudo apt-get install libmysqlclient-dev -y
             sudo apt-get install default-libmysqlclient-dev libpq-dev -y
             sudo apt-get install libgdal-dev libproj-dev gdal-bin python3-gdal cron \
             postgresql-client gettext postgresql postgresql-contrib postgis python3-psycopg2 -y
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Run test case
          command: |
            pipenv run python manage.py test

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint