version: 2.1

jobs:
  test-and-lint:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: python manage.py test
      - run:
          name: Build docker image
          command: |
            docker-compose build
            docker images
            docker container run --name shopwithcircleci shopwithcircleci python manage.py test

workflows:
  build-and-test-workflow:
    jobs:
      - test-and-lint