test-using-docker:
  docker:
    - image: cimg/python:3.10.5
  steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.14
    -run:
      name: Build Docker Image
      command: |
        docker compose up -d